Add simulcast notifications APIs
devalevenkatesh/amazon-chime-sdk-js pull request #1
Opened 2020-09-04 00:31 UTC by devalevenkatesh

**Issue #:** 

**Description of changes:**
- Add `SimulcastUplinkObserver` to provide update on changes in currently active simulcast uplink streams
- Update `AudioVideoObserver` with method to update on changes in remote videos available
- Update `AudioVideoControllerFacade` API to get remote videos available

Note: This PR is a draft PR. I will add unit tests and demo changes to complete this one.

**Testing**
- Have not included unit tests yet, will include once ready. Thus creating it as a draft PR.

1. Have you successfully run `npm run build:release` locally?
- Fails, I guess mostly due to the test threshold. But all existing tests pass.

2. How did you test these changes?
- Tested locally with demo browser app and logs. I will add demo changes and unit tests with this review based on feedback.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-04 21:07 UTC, alochbau-amzn commented on demos/browser/app/meetingV2/meetingV2.ts
> +    this.setupSimulcastUplinkPolicy(this.selfAttendeeId, logger, configuration);
I think it makes sense to put the if (this.enableSimulcast) check before calling this function.  Makes it clearer that this function only applies to when running simulcast.

2020-09-04 21:08 UTC, alochbau-amzn commented on demos/browser/app/meetingV2/meetingV2.ts
> +    if (this.activeSimulcastLayers !== simulcastLayers) {
Should we need to do this check?  The expectation is that this is only called if something changed.

2020-09-04 21:16 UTC, alochbau-amzn commented on src/task/ReceiveVideoStreamIndexTask.ts
> +      this.publishRemoteVideoAttendees(newAttendees);
My preference would be to call the observers in place rather then create a new method which only does that.   I see that is what is done in another spot in this module.

2020-09-04 21:17 UTC, alochbau-amzn commented on src/videostreamindex/DefaultVideoStreamIndex.ts
> +    const attendeeSet = new Set<string>();
Can you do away with the set and just use the array?  Use array.find or array.filter to determine if the attendeeId is already there.

2020-09-04 21:19 UTC, alochbau-amzn commented on src/videotile/VideoTileState.ts
> +import SimulcastLayers from '../simulcastlayers/SimulcastLayers';
Was it necessary to import this?  Only reason I ask is I don't see any other imports needed for the other variables.

2020-09-04 22:02 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    this.setupSimulcastUplinkPolicy(this.selfAttendeeId, logger, configuration);
Yes, I added the check inside `setupSimulcastUplinkPolicy` I will add it here instead. Thanks! Will change it.

2020-09-04 22:03 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    if (this.activeSimulcastLayers !== simulcastLayers) {
Ok I will check and update accordingly. I am not remembering if I got similar updates.

2020-09-04 22:03 UTC, devalevenkatesh commented on src/task/ReceiveVideoStreamIndexTask.ts
> +      this.publishRemoteVideoAttendees(newAttendees);
Cool, I can update inline rather than separating it out

2020-09-04 22:08 UTC, devalevenkatesh commented on src/videostreamindex/DefaultVideoStreamIndex.ts
> +    const attendeeSet = new Set<string>();
I used Set so that if this frequently updates then the search for attendeeId be O(1), if I use Array then it depends on the length which might affect performance. That's why.

2020-09-04 22:12 UTC, alochbau-amzn commented on src/videostreamindex/DefaultVideoStreamIndex.ts
> +    const attendeeSet = new Set<string>();
Ok, good with me.

2020-09-09 00:23 UTC, simmkyu requested changes
Overall, it's going in the right direction. We can discuss API naming with team. You can open PR in the public repo for team's inputs later.

2020-09-22 21:33 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    configuration.videoUplinkBandwidthPolicy = new SimulcastUplinkPolicy(selfAttendeeId, logger);
Thanks, I have changed as suggested here, resolving this and previous comment for this. Basically removed selfAttendeeId as a instance variable.

2020-09-22 21:34 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    this.simulcastUplinkPolicy = configuration.videoUplinkBandwidthPolicy as SimulcastUplinkPolicy;
Since, the recent changes, I do not anymore set the `SimulcastUplinkPolicy` in the demo meeting app, just add the `SimulcastObserver` after the `audioVideo.start()`. Thanks!

2020-09-22 21:34 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    console.log('[DEMO] Available remote videos changed', attendees);
Updated to use `this.log` everywhere for this PR. Thanks!

2020-09-22 21:35 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +    // compare the renditions to existing received and update if different
Yup I am currently just logging the change and have removed the `activeSimulcastLayers` instance variable.

2020-09-22 21:36 UTC, devalevenkatesh commented on package.json
> +    "test:single": "cross-env TS_NODE_CACHE=false nyc mocha -rv ts-node/register",
Sure, removed this script, thanks for catching it.

2020-09-22 21:37 UTC, devalevenkatesh commented on src/audiovideocontroller/DefaultAudioVideoController.ts
> +    if (!this.meetingSessionContext) {
Nice, removed the check!

2020-09-22 21:45 UTC, devalevenkatesh commented on src/audiovideocontroller/AudioVideoControllerFacade.ts
> +  getRemoteVideosAvailable(): { attendeeId: string; externalUserId: string }[];
So, as per Andrew's [design](https://quip-amazon.com/kis6ANIzBxdj/jsSDK-Video-Stream-Notification-and-Query-API), it says to add `getRemoteVideosAvailable` to the `AudioVideoFacade` API. This means to update the `AudioVideoControllerFacade` interface so I have added it here. Otherwise, it wont be exposable, correct?

2020-09-22 21:49 UTC, devalevenkatesh commented on src/audiovideocontroller/DefaultAudioVideoController.ts
> +      if (
Yes, I have removed the `instanceof` check since we are not allowing to override as well as not overriding the `SimulcastUplinkPolicy`. This check was in-place since I was adding the simulcast observer to the newly instantiated `SimulcastUplinkPolicy` in the demo app. 

Now we have implemented to add the simulcast observers through `AudioVideoControllerFacade` and `AudioVideoFacade`.

2020-09-22 21:50 UTC, devalevenkatesh commented on src/videostreamindex/DefaultVideoStreamIndex.ts
> +  allVideoSendingAttendeesExcludingSelf(
since this is an internal API for now I am skipping as discussed. But I agree on the suggestion here.

2020-09-22 21:51 UTC, devalevenkatesh commented on src/simulcastlayers/SimulcastLayers.ts
> +enum SimulcastLayers {
Yup changed to `SimulcastLayer` thanks!

2020-09-22 21:52 UTC, devalevenkatesh commented on test/audiovideocontroller/DefaultAudioVideoController.test.ts
> +    it('should return an array', async () => {
Yup true, I have changed the test check for the expected attendees and compare the return value. Thanks for catching and pointing this out.

2020-09-22 21:59 UTC, devalevenkatesh commented on src/videouplinkbandwidthpolicy/VideoUplinkBandwidthPolicy.ts
> +  removeObserver?(observer: SimulcastUplinkObserver): void;
So implement this, I did the following changes:
1. Created `SimulcastUplinkPolicy` interface that extends `VideoUplinkBandwidthPolicy`.
2. Updated the `SimulcastUplinkPolicy` class name to `DefaultSimulcastUplinkPolicy`.
3. `DefaultSimulcastUplinkPolicy` now implements the `SimulcastUplinkPolicy`.
4. Updated the unit tests to incorporate these changes.
5. Since this policy is only used when simulcast feature is enabled, the `meetingSessionContext` in `DefaultAudioVideoController` uses casting to use `VideoUplinkBandwidthPolicy` as `SimulcastUplinkPolicy`

Thanks, this is better design and consistent with SDK's pattern now.

2020-09-22 22:00 UTC, devalevenkatesh commented on src/videouplinkbandwidthpolicy/SimulcastUplinkPolicy.ts
> +  private activeSimulcastLayers: SimulcastLayers;
Yup changed it: `activeSimulcastLayers` => `activeSimulcastLayer`, thanks!

2020-09-22 22:05 UTC, alochbau-amzn commented on src/simulcastlayers/SimulcastLayers.ts
> +enum SimulcastLayers {
Seems plural could be the correct fit here as it is an enum specifying which simulcast layers are active.  Some of the enum entries represent multiple simulcast layers, not just one.

2020-10-16 21:51 UTC, simmkyu approved these changes

2020-10-16 21:58 UTC, alochbau-amzn approved these changes

2020-12-14 23:02 UTC, closed without merging