Add Samsung Internet browser support
devalevenkatesh/amazon-chime-sdk-js pull request #5
Opened 2020-12-15 22:55 UTC by devalevenkatesh

**Issue #:**
NA.

**Description of changes:**
- Changes to `DefaultBrowserBehavior` to add Samsung browser to supported browser's list and to add it to chrome like list.
- Add Samsung browser check for not adding `exact` in the media constraints when `getUserMedia` is called.
- Adds Samsung Internet browser user agent unit test.
- Adds FAQs for: 
  - Android 11 and Chromium 83 ICE gathering bug.
  - Amazon Voice Focus use in Samsung Internet browser.

**Testing**

1. Have you successfully run `npm run build:release` locally? Yes
2. How did you test these changes? Tested locally and deploying the demo application.
3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it? Yes, you can use `demo/browser` app to test this.
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved? No.
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved? No.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-16 00:16 UTC, simmkyu requested changes

2020-12-16 00:16 UTC, simmkyu commented on guides/07_FAQs.md
> +### Does the Amazon Voice Focus support the Samsung Internet browser?
- nit: Remove `the` from `the Amazon Voice Focus`. The guide refers to it without `the`.
  https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/09_Amazon_Voice_Focus.md

2020-12-16 00:16 UTC, simmkyu commented on guides/07_FAQs.md
> +The Amazon Voice Focus technically works with the Samsung Internet Browser. But, we observed it to be not fast enough. Please check the Amazon Voice Focus [browser compatibility matrix](https://githu
- nit: `Samsung Internet Browser` => `Samsung Internet browser` for consistency.
- `technically works` and `not fast enough` are a bit ambiguous. How about the following? Feel free to rephrase.

> Yes, Amazon Voice Focus supports the Samsung Internet browser (Chromium 83 or lower). However, it leads to a poor user experience because the preferred Chromium version is 87 or higher. Please check ...

By the way, do you have any website or official spec that explains Chromium versions the Samsung Internet browsers are using?

2020-12-16 00:16 UTC, simmkyu commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
Please double check that you acquire the requested device. Without `exact`, the browser uses the `ideal` keyword implicitly so that it might give you another available device.

2020-12-16 00:19 UTC, anuranduttaroy commented on demos/browser/package.json
> +    "aws-sdk": "^2.811.0",
Is this intended?

2020-12-16 00:20 UTC, anuranduttaroy commented on guides/07_FAQs.md
> +This is a bug on Android 11 running Chromium 83 based browsers. You will observe this issue in the Samsung Internet browser (Version 13) since it is based on Chromium 83. Please check [ICE gathering
observe this issue **on the** Samsung Internet browser

"in the" -> "on the"

2020-12-16 00:21 UTC, anuranduttaroy commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +    'samsung',
The last `,` is not required

2020-12-16 00:23 UTC, anuranduttaroy commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
This was working for my S10 + Samsung Browser. Did you check it works without the `exact` keyword in Samsung browser + non pixel phone combination?

2020-12-16 00:35 UTC, devalevenkatesh commented on guides/07_FAQs.md
> +The Amazon Voice Focus technically works with the Samsung Internet Browser. But, we observed it to be not fast enough. Please check the Amazon Voice Focus [browser compatibility matrix](https://githu
I had checked and could find official link which mentions only Samsung Internet browser version, but, not chromium it uses:
https://developer.samsung.com/internet/release-note.html

The Wikipedia does not have updated information after version 12:
https://en.wikipedia.org/wiki/Samsung_Internet

2020-12-16 00:39 UTC, devalevenkatesh commented on demos/browser/package.json
> +    "aws-sdk": "^2.811.0",
This is updated when I ran the demo app, will remove the update. Thanks!

2020-12-16 00:41 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
Yeah, this should have got tested in today's standup. I also asked Vidya to re-check if she got video preview, she was on a Samsung device.

2020-12-16 00:42 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +    'samsung',
Got it, thanks! Updated it.

2020-12-16 00:42 UTC, devalevenkatesh commented on guides/07_FAQs.md
> +This is a bug on Android 11 running Chromium 83 based browsers. You will observe this issue in the Samsung Internet browser (Version 13) since it is based on Chromium 83. Please check [ICE gathering
Got it, thanks! Updated it.

2020-12-16 00:46 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
Ohh, Ok can you help me how can I check if it using the correct `deviceId`?

2020-12-16 00:46 UTC, devalevenkatesh commented on guides/07_FAQs.md
> +The Amazon Voice Focus technically works with the Samsung Internet Browser. But, we observed it to be not fast enough. Please check the Amazon Voice Focus [browser compatibility matrix](https://githu
Have updated the sentence, thanks!

2020-12-16 00:47 UTC, devalevenkatesh commented on guides/07_FAQs.md
> +### Does the Amazon Voice Focus support the Samsung Internet browser?
Ok ok, have removed `the` and just kept `Amazon Voice Focus`.

2020-12-16 00:47 UTC, devalevenkatesh commented on guides/07_FAQs.md
> +### I notice that I am not able to join an Amazon Chime JS SDK meeting from an Android 11 device running Chromium 83 based browsers, like Samsung Internet (Version 13) for Android or Chrome (Version
Got it, thanks! Have updated it.

2020-12-16 00:55 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
I think this should work: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getConstraints 

Will check further.

2020-12-16 01:10 UTC, ltrung commented on demos/browser/package.json
> +    "aws-sdk": "^2.811.0",
I dont think this cause any issue so you could leave it

2020-12-16 22:41 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +      this.isSamsungInternet() ||
I have removed the check `this.isSamsungInternet()` from `requiresNoExactMediaStreamConstraints` and added `requiresGroupIdMediaStreamConstraints` method to handle samsung internet browser.

2020-12-16 22:44 UTC, devalevenkatesh commented on demos/browser/package.json
> +    "aws-sdk": "^2.812.0",
Please let me know if to remove this. Thanks!

2020-12-16 22:45 UTC, devalevenkatesh commented on src/browserbehavior/DefaultBrowserBehavior.ts
> +    samsung: 12,
@anuranduttaroy The comma gets inserted when we run `npm run build:release`.

2020-12-16 23:01 UTC, simmkyu requested changes

2020-12-16 23:15 UTC, devalevenkatesh commented on demos/browser/package.json
> +    "aws-sdk": "^2.812.0",
Yup, cool thanks!

2020-12-16 23:17 UTC, devalevenkatesh commented on src/devicecontroller/DefaultDeviceController.ts
> +        trackConstraints.deviceId = device;
Nice, thanks for the suggestion.

2020-12-16 23:18 UTC, devalevenkatesh commented on demos/browser/app/meetingV2/meetingV2.ts
> +        if (showPreview) {
Yeah, thanks for the catch, I was trying something and may have left this. Have reverted it.

2020-12-16 23:58 UTC, anuranduttaroy approved these changes

2020-12-17 00:50 UTC, simmkyu approved these changes

2021-04-16 19:44 UTC, closed without merging